#!/usr/bin/env python3


import argparse
import os
import shutil


def get_args() -> argparse.Namespace:
    """
    Return arguments from the command line
    """
    parser = argparse.ArgumentParser()
    parser.add_argument("service")

    return parser.parse_args()


def clean(service: str):
    shutil.rmtree(os.path.join(service, "build"))


if __name__ == "__main__":
    args = get_args()

    clean(args.service)